
---
- hosts: all
  become: true

  tasks:
  - name: print gathered facts
    ansible.builtin.debug:
      var: ansible_facts

  - name: shutdown ubuntu servers
    ansible.builtin.command: /sbin/shutdown -t now
    when:
     ansible_facts['os_family'] == "Debian"

  - name: shutdown amazon linux server
    ansible.builtin.command: /sbin/shutdown -t now
    when:
     ansible_facts["os_family"] == "RedHat"
